# name of forwarder
NAME: f99

BARRIER_TIMEOUT: 30

# logging directory
LOGGING_DIR: /var/log/iip

# working directory where cfitio and header files are fetched/assembled
WORK_DIR: /var/tmp/data

# daq partition name
# Note: remember to check if partition name exists in the keyword below from
# line 24-26. Otherwise, there will be weird error.
PARTITION: lat
FOLDER: raw

# forwarder mode [live|catchup]
MODE: live

# LCA-13501 segment order
PATTERN:
    DATA_SEGMENT_NAME:
        science: [ 10, 11, 12, 13, 14, 15, 16, 17, 07, 06, 05, 04, 03, 02, 01, 00 ]
        guide: [ 10, 11, 12, 13, 14, 15, 16, 17, 07, 06, 05, 04, 03, 02, 01, 00 ]
        # old wavefront: [ 10, 11, 12, 13, 14, 15, 16, 17 ]
        wavefront: [ 10, 11, 12, 13, 14, 15, 16, 17, 07, 06, 05, 04, 03, 02, 01, 00 ]
    DATA_SEGMENT:
        #SCIENCE: [ 15, 14, 13, 12, 11, 10, 9, 8, 0, 1, 2, 3, 4, 5, 6, 7 ]
        science: [ 8, 9, 10, 11, 12, 13, 14, 15, 7, 6, 5, 4, 3, 2, 1, 0 ]
        guide: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 ]
        #old wavefront: [ 0, 1, 2, 3, 4, 5, 6, 7 ]
        wavefront: [ 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 ]
    DATA_SENSOR:
        science: [ 2, 1, 0 ]
        guide: [ 1, 0 ]
        wavefront: [ 1, 0 ]
    XOR:
        science: 0x1FFFF
        guide: 0x20000
        wavefront: 0x20000

# daq location patterns in the hardware. These values are pre-defined here so
# that forwarder can throw exception when someone gives wrong "raft/ccd"
# location. Currently daq hardware segfaults when wrong argument is given to
# constructor
lat: [ 00/0 ]
ncsa-comcam: [ 22/0, 22/1, 22/2 ]
cam-comcam: [ 22/0, 22/1, 22/2 ]

# rabbitMQ broker address
BASE_BROKER_ADDR: auxtel-archiver.cp.lsst.org:5672/%2ftest_at
#BASE_BROKER_ADDR: 141.142.238.15:5672/test_cu

# @deprecated_soon
# forwarder queue to listen to RabbitMQ messages. This is static queue, meaning
# someone has to create this queue in advance for forwarder to work. In the
# future, forwarder is gonna create queues on the fly when it starts up.
CONSUME_QUEUE: f99_consume

# rabbitMQ archivecontroller queue
ARCHIVE_QUEUE: archive_ctrl_consume

# telemetry queue for publishing telemetry messages from forwarder
TELEMETRY_QUEUE: telemetry_queue

# redis database configuration for handling heartbeat and storing information

REDIS:
    REMOTE:
        HOST: auxtel-archiver.cp.lsst.org
        PORT: 6379
        DB: 15
    LOCAL:
        HOST: auxtel-archiver.cp.lsst.org
        PORT: 6379
        DB: 2

# timeout for forwarder to send keepalive to associated CSC
SECONDS_TO_UPDATE: 3

# timeout for forwarder to check keepalive of associated CSC
SECONDS_TO_EXPIRE: 10

# file transfer protocol
# bbcp is listed as an example. Another option is scp
# -f, forces the copy
# -n, does not use DNS to resolve IP address
# -s, number of streams to use
#XFER_OPTION: bbcp -f -n -s 1 -i ~/.ssh/id_rsa
#XFER_OPTION: scp -i ~/.ssh/id_rsa
XFER_OPTION: scp
